// <auto-generated />
using System;
using Marmelade.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Marmelade.Data.Migrations
{
    [DbContext(typeof(DatenbankContext))]
    [Migration("20231215185127_2nd")]
    partial class _2nd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Marmelade.Data.ApiEinstellung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthenticationSchluessel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApiEinstellungen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthenticationSchluessel = "ChangeMe",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(7090),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(7090),
                            UpdatedBy = "Marco Kittel"
                        });
                });

            modelBuilder.Entity("Marmelade.Data.Lagergegenstand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LagerortId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Lagerzeitpunkt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Menge")
                        .HasColumnType("float");

                    b.Property<string>("Mengenbezeichner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LagerortId");

                    b.ToTable("Lagergegenstand");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beschreibung = "Frische Fruchtmarmelade",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6330),
                            CreatedBy = "Marco Kittel",
                            LagerortId = 1,
                            Lagerzeitpunkt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6370),
                            Menge = 500.0,
                            Mengenbezeichner = "Gramm",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6360),
                            Name = "Melonen Marmelade",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 2,
                            Beschreibung = "Frische Fruchtmarmelade",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6370),
                            CreatedBy = "Marco Kittel",
                            LagerortId = 5,
                            Lagerzeitpunkt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6370),
                            Menge = 750.0,
                            Mengenbezeichner = "Gramm",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6370),
                            Name = "Erdbeer Marmelade",
                            UpdatedBy = "Marco Kittel"
                        });
                });

            modelBuilder.Entity("Marmelade.Data.Lagerort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Lagerorte");

                    b.HasData(
                        new
                        {
                            Id = 13,
                            Beschreibung = "Kühlschrank C",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6500),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6500),
                            Name = "C1",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 14,
                            Beschreibung = "Kühlschrank C",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6500),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6500),
                            Name = "C2",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 15,
                            Beschreibung = "Kühlschrank C",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6510),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6510),
                            Name = "C3",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 16,
                            Beschreibung = "Kühlschrank C",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6510),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6510),
                            Name = "C4",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 17,
                            Beschreibung = "Kühlschrank C",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6510),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6510),
                            Name = "C5",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 1,
                            Beschreibung = "Kühlschrank A",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6450),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6450),
                            Name = "A1",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 2,
                            Beschreibung = "Kühlschrank A",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6460),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6460),
                            Name = "A2",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 3,
                            Beschreibung = "Kühlschrank A",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6460),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6460),
                            Name = "A3",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 4,
                            Beschreibung = "Kühlschrank A",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6460),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6460),
                            Name = "A4",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 5,
                            Beschreibung = "Kühlschrank A",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6470),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6470),
                            Name = "A5",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 6,
                            Beschreibung = "Kühlschrank A",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6470),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6470),
                            Name = "A6",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 7,
                            Beschreibung = "Kühlschrank B",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6470),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6480),
                            Name = "B1",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 8,
                            Beschreibung = "Kühlschrank B",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6480),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6480),
                            Name = "B2",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 9,
                            Beschreibung = "Kühlschrank B",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6480),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6480),
                            Name = "B3",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 10,
                            Beschreibung = "Kühlschrank B",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6490),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6490),
                            Name = "B4",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 11,
                            Beschreibung = "Kühlschrank B",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6490),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6490),
                            Name = "B5",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 12,
                            Beschreibung = "Kühlschrank B",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6500),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6500),
                            Name = "B6",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 18,
                            Beschreibung = "Kühlschrank G",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6520),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6520),
                            Name = "G1",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 19,
                            Beschreibung = "Kühlschrank G",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6530),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6530),
                            Name = "G2",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 20,
                            Beschreibung = "Garage",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6530),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6530),
                            Name = "GA",
                            UpdatedBy = "Marco Kittel"
                        },
                        new
                        {
                            Id = 21,
                            Beschreibung = "Keller",
                            CreatedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6530),
                            CreatedBy = "Marco Kittel",
                            ModifiedAt = new DateTime(2023, 12, 15, 19, 51, 27, 377, DateTimeKind.Local).AddTicks(6530),
                            Name = "KE",
                            UpdatedBy = "Marco Kittel"
                        });
                });

            modelBuilder.Entity("Marmelade.Data.Lagergegenstand", b =>
                {
                    b.HasOne("Marmelade.Data.Lagerort", "Lagerort")
                        .WithMany("Lagergegenstand")
                        .HasForeignKey("LagerortId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Lagerort");
                });

            modelBuilder.Entity("Marmelade.Data.Lagerort", b =>
                {
                    b.Navigation("Lagergegenstand");
                });
#pragma warning restore 612, 618
        }
    }
}
