name: .NET Core Desktop
on:
  workflow_dispatch

jobs:

  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest
    env:
      Solution_Name: Marmelade.sln  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Abhängigkeiten holen
      run: dotnet restore
    - name: Build app for release
      run: dotnet build Marmelade/Marmelade.Api.csproj -t:rebuild --configuration Release 
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Auf den Server kopieren
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATEKEY }}
        source: "Marmelade/bin/Release/net7.0/Marmelade.Api.dll"
        target: "/home/${{ secrets.USER }}"
    - name: Auf den Server kopieren 2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATEKEY }}
        source: "Marmelade.Data/bin/Release/net7.0/Marmelade.Data.dll"
        target: "/home/${{ secrets.USER }}"        
