name: .NET Core Desktop
on:
  workflow_dispatch

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Marmelade.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0


    - name: Abhängigkeiten holen
      run: dotnet restore
    - name: Build app for release
      run: dotnet build Marmelade/Marmelade.Api.csproj -t:rebuild --configuration Release 
